limit:
  lower: 0.0
  upper: 1.3
  effort: 2.2
  velocity: 3.35

origin:
  single_bracket: { x: 0.0, y: 0.0, z: 0.05 }
  moment_arm: { x: -0.017, y: 0.0, z: 0.055 }
  truss_arm: { x: -0.0075, y: 0.0, z: 0.0715 }
  finger_tip: { x: -0.0256, y: 0.0, z: 0.04868 }
  flex_finger: { x: 0.03059, y: 0.0, z: 0.0172 }
  grasp_frame: { x: 0.0, y: 0.0, z: 0.14 }

inertial:
  body: {mass: 0.65, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}
  single_bracket: {mass: 0.09, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}
  moment_arm: {mass: 0.001, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}
  truss_arm: {mass: 0.001, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}
  finger_tip: {mass: 0.001, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}
  flex_finger: {mass: 0.001, ixx: 0.001, iyy: 0.001, izz: 0.001, ixy: 0.0, ixz: 0.0, iyz: 0.0}

kinematics:
  offset: -0.772
